### PR TITLE
Blog about new i18n

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
Awesome! It *might* be nice to link to womp - or some other sample application - in order to underscore the configuration points into a kraken application.

**Comment by aredridel** [comment]
Oooh, interesting point. I'll think about that. We need an upgrade guide -- I wrote some. Maybe I can recycle that.

**Comment by grawk** [comment]
I'd like to refer to this blog post from one of the construx module's README files. Is it OK to go ahead and publish without an upgrade guide?

**Comment by aredridel** [comment]
Yeah! that can be another post.

**Comment by grawk** [comment]
In that case :+1:

**Pull request merged**
