### PR TITLE
Add Adaro and Makara docs

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
There may be problems with the code examples in this build; I'm not sure if Github is using Github flavored markdown for it, or if I'll have to go full on pygments.

**Comment by grawk** [comment]
The below layout issue is unfortunate... I wonder, in lieu of fixing the root cause, if you could shorten the title... Otherwise, maybe we can address the root cause in this PR. I'm looking but haven't figured it out yet.
krakenjs-com-navissue

**Comment by grawk** [comment]
Something about the .affix class (adding `position: fixed` to div#documentation-nav) is doing this.

**Comment by aredridel** [comment]
Yeah, I was going to tackle that in the morning! That's #37.

**Comment by grawk** [comment]
I would say it's a blocker just because this is such an unpleasant layout issue

**Comment by grawk** [comment]
Some of the code blocks are not rendering properly for me locally. I thin the ` ` ` md isn't working as it should.

I'm not super familiar with jekyll etc but using the `{% highlight javascript %}` markup seems to work.

**Comment by aredridel** [comment]
Yeah. I wasn't sure if Github would use Github Markdown in pages, while Jekyll won't, or not.

The highlighter strips leading whitespace which is super annoying.

**Comment by aredridel** [comment]
There. Switched to redcarpet and it should render the code blocks suitably.

**Comment by grawk** [comment]
That's awesome! So my only little nit is that the code in the code blocks are indented 8 spaces. They'd look better without the left margin. Otherwise though :+1: feel free to merge with or without the code margin changes.

**Comment by aredridel** [comment]
The reason I left them indented is that that way they match the generated json -- you can copy and paste into an existing generated app, with no indentation fixes.

**Pull request merged**
